name: Release Workflow
on: [create]

permissions:
  contents: write

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set kvm permissions
        run: sudo chmod 666 /dev/kvm
      - name: Set net permissions
        run: sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip ./bin/clh-net-wrapper
      - name: Install packages
        run: sudo apt-get install -y qemu-utils lz4 mtools qemu-system
      - name: Check kvm
        run: kvm-ok
      - name: Download cloud-hypervisor
        run: wget https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v44.0/cloud-hypervisor-static && chmod +x cloud-hypervisor-static
      - name: Download firmware
        run: wget https://github.com/cloud-hypervisor/rust-hypervisor-firmware/releases/download/0.5.0/hypervisor-fw
      - name: Download ubuntu
        run: wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
      - name: Resize image
        run: qemu-img resize noble-server-cloudimg-amd64.img 8G
      - name: Generate init image
        run: ./create-cloud-init.sh
      - name: Convert
        run: qemu-img convert -p -f qcow2 -O raw noble-server-cloudimg-amd64.img noble-server-cloudimg-amd64.raw && rm noble-server-cloudimg-amd64.img
      - name: Prepare image
        run: clh-net-wrapper "$PWD/cloud-hypervisor" --cpus boot=4 --console off --serial tty --memory size=8192M --kernel "$PWD/hypervisor-fw" "--disk" "path=$PWD/noble-server-cloudimg-amd64.raw" "path=$PWD/init.img" "--net" "fd=3,offload_tso=off,offload_ufo=off,offload_csum=off"
      - name: Compress
        run: lz4 -12 noble-server-cloudimg-amd64.raw noble-server-cloudimg-amd64.lz4 && rm noble-server-cloudimg-amd64.raw
      - name: Split
        run: split -b 1G noble-server-cloudimg-amd64.lz4 noble-server-cloudimg-amd64.lz4.part
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "noble-server-cloudimg-amd64.lz4.part*"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true