name: Release Workflow
on: [create]

permissions:
  contents: write

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set kvm permissions
        run: sudo chmod 666 /dev/kvm
      - name: Install packages
        run: sudo apt-get install -y qemu-utils lz4 mtools qemu-system
      - name: Check kvm
        run: kvm-ok
      - name: Download ubuntu
        run: wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64-disk-kvm.img -O ubuntu.img
      - name: Resize image
        run: qemu-img resize ubuntu.img 8G
      - name: Generate init image
        run: ./create-cloud-init.sh
      - name: Prepare image
        run: qemu-system-x86_64 -enable-kvm -m 4096 -drive file=ubuntu.img,media=disk,if=virtio -drive file=init.img,media=disk,if=virtio -cpu host -display none -serial mon:stdio -nic user,model=virtio-net-pci -smp 4
      - name: Convert
        run: qemu-img convert -p -f qcow2 -O raw ubuntu.img ubuntu.raw && rm ubuntu.img
      - name: Compress
        run: lz4 -12 ubuntu.raw ubuntu.lz4 && rm ubuntu.raw
      - name: Split
        run: split -b 1G ubuntu.lz4 jammy-server-cloudimg-amd64.lz4.part
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "jammy-server-cloudimg-amd64.lz4.part*"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true