name: Release Workflow
on: [create]

permissions:
  contents: write

jobs:
  release:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install packages
        run: sudo apt-get install -y qemu-utils lz4 mtools qemu-system
      - name: Check kvm
        run: kvm-ok
      - name: Download ubuntu
        run: wget https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
      - name: Resize image
        run: qemu-img resize noble-server-cloudimg-amd64.img 10G
      - name: Generate init image
        run: ./create-cloud-init.sh
      - name: Prepare image
        run: qemu-system-x86_64 -enable-kvm -m 2048 -drive file=image.img,media=disk,if=virtio -drive file=noble-server-cloudimg-amd64.img,media=disk,if=virtio -cpu host -display curses -serial mon:stdio -nic user,model=virtio-net-pci -smp 4
      - name: Convert
        run: qemu-img convert -p -f qcow2 -O raw noble-server-cloudimg-amd64.img noble-server-cloudimg-amd64.raw && rm noble-server-cloudimg-amd64.img
      - name: Compress
        run: lz4 -12 noble-server-cloudimg-amd64.raw noble-server-cloudimg-amd64.lz4 && rm noble-server-cloudimg-amd64.raw
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.lz4"
          tag: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true